name: My First Workflow
on: workflow_dispatch
jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      -name: My First Job
      run: echo "Job Starting"
      -name: My First Instructions
      run: ls /
      -name: End of First Job
      run: echo "That's All Folks!"
